review and make first edits

diff --git a/sas_log_check b/sas_log_check
--- a/sas_log_check
+++ b/sas_log_check
@@ -19,11 +19,13 @@
 #    June 2017 - S. Elser - created a base script for log checking that can be called by other scripts
 #    July 2017 - S. Elser - added the rootname variable to allow parameters to have extensions
 #    Sept 2018 - S. Elser - documented additional checks and added a new one for FATAL errors, version is now 1.1
+#    Apr  2019 - S. Elser - cleaned up for public release, sorted checks by priority, version is now 1.2
+#    May  2019 - S. Elser - added additional low priority checks provided by A. Caruso, version is now 1.3
 #
 # Execution:
 #    Prints date of log file to record
 #    Runs a tail command so can see the runtime stats at bottom of .log
-#    Runs the SAEB Log Checker set of KSH code
+#    Runs the Log Checker set of KSH code
 
    #  this line strips the filename of its extension
    rootname=${1%.*}
@@ -38,7 +40,7 @@
    tail     $rootname.log
 
    echo    "*********************************************"
-   echo    "SAEB Log Checker Start  [Current Version: 1.1]"
+   echo    "Log Checker Start  [Current Version: 1.3]"
    echo    ""
 
 
@@ -54,9 +56,9 @@
       # note:  R output begins every line with "Warning: R:" so that specific case needed to be ignored
       # S. Elser: Also filtering out several Warnings created by user code or that cause unnecessary messages
       grep -i warning: $i |                                      \
-         grep -iv "warning: r:" |                                \
-         grep -iv "%put warning:" |                              \
-         grep -iv "WARNING: Unable to copy SASUSER registry" |   \
+         grep -iv "Warning: R:" |                                \
+         grep -iv "%put Warning:" |                              \
+         grep -iv "Warning: Unable to copy SASUSER registry" |   \
          grep -iv "Warning: The minimum data value" |            \
          grep -iv "Warning: Limit set by ERRORS= option reached" > /dev/null
          if [ $? = 0 ]; then
@@ -68,19 +70,9 @@
             echo "SEVERE:   Uninit                in $i"  
          fi
 
-      grep -i converted $i | grep -iv "files will be automatically converted" > /dev/null
-         if [ $? = 0 ]; then
-            echo "LOW:      Converted             in $i" 
-         fi
-
       grep -i truncate $i > /dev/null
          if [ $? = 0 ]; then
-            echo "SEVERE:     Truncate            in $i" 
-         fi
-
-      grep -i "Invalid argument" $i > /dev/null
-         if [ $? = 0 ]; then
-            echo "HIGH:     Invalid argument      in $i" 
+            echo "SEVERE:   Truncate              in $i" 
          fi
 
       grep -i "repeats of BY values" $i > /dev/null
@@ -88,16 +80,19 @@
             echo "SEVERE:   Repeats of BY values  in $i" 
          fi
 
-      ## past here are ones from Lauren via email 5/22/2014
-
-      grep -i "Character values" $i > /dev/null
-         if [ $? = 0 ]; then
-            echo "LOW:      Character values      in $i" 
-         fi
+	   grep -i "Fatal:" $i > /dev/null
+		   if [ $? = 0 ]; then
+	 	      echo "SEVERE:   Fatal execution error in $i"
+		   fi
 
       grep -i "End of line" $i > /dev/null
          if [ $? = 0 ]; then
             echo "HIGH:     End of line           in $i" 
+         fi
+
+      grep -i "Invalid argument" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH:     Invalid argument      in $i" 
          fi
 
       grep -i "does not exist" $i | grep -iv "NOTE: BASE data set does not exist."> /dev/null
@@ -120,14 +115,35 @@
             echo "HIGH:     Multiple lengths      in $i" 
          fi
 
+      grep -i "Not resolved" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH:     Not resolved          in $i" 
+         fi
+
+      grep -i "Invalid numeric data" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH:     Invalid numeric data  in $i" 
+         fi
+
+      grep -i "Invalid data" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH:     Invalid data          in $i" 
+         fi
+
+      # added for custom error messages
+      grep -i "Custom note:" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH:     Check for CUSTOM NOTE in $i" 
+         fi
+
       grep -i "No observations" $i > /dev/null
          if [ $? = 0 ]; then
             echo "LOW:      No observations       in $i" 
          fi
 
-      grep -i "Not resolved" $i > /dev/null
+      grep -i "Character values" $i > /dev/null
          if [ $? = 0 ]; then
-            echo "HIGH:     Not resolved          in $i" 
+            echo "LOW:      Character values      in $i" 
          fi
 
       grep -i " 0 observations" $i > /dev/null
@@ -136,49 +152,46 @@
             echo "          MIGHT BE OK IF TRAPPING ERRORS IN A DATASET"
          fi
 
-      # these are the ones SAEB found
-
-      grep -i "Invalid numeric data" $i > /dev/null
+      grep -i converted $i | grep -iv "files will be automatically converted" > /dev/null
          if [ $? = 0 ]; then
-            echo "HIGH:     Invalid numeric data  in $i" 
+            echo "LOW:      Converted             in $i" 
          fi
 
-      # added 08/2017 by J. Posey
-      grep -i "Invalid data" $i > /dev/null
+      grep -i _error_ $i > /dev/null
          if [ $? = 0 ]; then
-            echo "HIGH:     Invalid data          in $i" 
+            echo "LOW:      _error_               in $i"
          fi
 
-      # added 09/2017 by S. Elser for custom error messages
-      grep -i "SAEB NOTE:" $i > /dev/null
+      grep -i "division by zero" $i > /dev/null
          if [ $? = 0 ]; then
-            echo "HIGH:     Check for SAEB NOTE   in $i" 
+            echo "LOW:      division by zero      in $i"
          fi
 
-	  # discovered 09/2018 by J. Posey and added by S. Elser
-	  grep -i "FATAL:" $i > /dev/null
-		 if [ $? = 0 ]; then
-		    echo "SEVERE:   Fatal execution error in $i"
-		 fi
+      grep -i "a missing value" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "LOW:      a missing value       in $i" 
+         fi
 
-      # added 06/2017 by S. Elser for checking R code executed in SAS
-      if [[ -n "$2" && $2 = "rlang" ]]; then
-         # The following checks are only for programs with R code and only searches the lines
-         # that begin in "WARNING: R:". R ERRORS are caught naturally by the SAS ERROR message.
-         grep -i "warning: r:" $i | grep -i "error" > /dev/null
-            if [ $? = 0 ]; then
-               echo "HIGH: (R) Error                 in $i" 
-            fi
-      fi
+      grep -i "not permitted" $i > /dev/null
+         if [ $? = 0 ]; then
+            echo "LOW:      not permitted         in $i" 
+         fi
+
+      # The following checks are only for programs with R code and only searches the lines
+      # that begin in "WARNING: R:". R ERRORS are normally caught by the SAS ERROR message.
+      grep -i "Warning: R:" $i | grep -i "error" > /dev/null
+         if [ $? = 0 ]; then
+            echo "HIGH: (R) Error                 in $i" 
+         fi
 
    done
 
    echo    ""
-   echo    "SAEB Log Checker Complete for $rootname.sas"
+   echo    "Log Checker Complete for $rootname.sas"
    echo    "**********************************************************************"
 
-# The bulk of the log checking came from Chris Boniface program 
-# recd email 3/18/2014 jmp
+# The bulk of the log checking came from Chris Boniface program, 3/18/2014
+#
 # ERROR is capitalized to allow program comments and varnames to have error 
 # contained within
 # other checks use -i for ignore case
